### ISSUE TITLE
Parsing Micheline expression

### ISSUE THREAD

**Issue by murbard** [baking-bad/pytezos#105]
Trying the MichelsonParser class in pytezos:

```python
p = pytezos.michelson.grammar.MichelsonParser()
p.parse('Pair 1 2')
```
yields
{'prim': 'Pair', 'args': [{'int': '1'}, {'int': '2'}]}

This ignores the possibility that the integers may refer to types or bigmaps... I understand this is just the parsing step, but how does one get further and get a "real" python value out of storage and the type of storage?

**Comment by m-kus** [comment]
This is just a conversion from Michelson/Micheline to the JSON notation. In order to get a Python object we additionally parse the according type expression (either parameter or storage) and then simultaneously traverse value and type trees.  
In your particular case if the type of the type node is `big_map` we will treat the according value node as empty dict `{}`

**Comment by m-kus** [comment]
The Michelson <-> Python types bijection was revised in #138 and now is based on a hierarchy of [type classes](https://pytezos.org/types.html).  
To illustrate the given example:
```
>>> from pytezos import michelson_to_micheline
>>> from pytezos.michelson.types.base import MichelsonType

>>> ty = MichelsonType.match(michelson_to_micheline("pair big_map nat"))
>>> res = ty.from_micheline_value(michelson_to_micheline("Pair 1 2"))
>>> res
({} * 2)
