### ISSUE TITLE
Incorrect tx Counter with multiple transactions 

### ISSUE THREAD

**Issue by trolleps** [baking-bad/pytezos#154]
Autofill() fills incorrect counter value for 2nd and following transactions when I send multiple not-batched transactions

**Comment by m-kus** [comment]
@droserasprout some contex on the issuet:

What is counter: 
https://tezos.stackexchange.com/questions/2321/what-is-an-operation-counter

Counter in-the-past/in-the-future issue: https://tezos.stackexchange.com/questions/1856/operation-injected-to-node-but-not-added-to-blockchain-wallet-counter-error/1954#1954

Operation stuck in mempool & counter: https://tezos.stackexchange.com/questions/1717/operation-not-included-due-to-0-fees-now-counter-is-stuck?rq=1

Currently counter is tracked in the scope of one operation group, and the workflow is the following:
1. Get current account counter from the node context (applied state)
2. For each operation in the group increment and assign counter
3. Reset pytezos context after injection

The problem:
At stage 1 the operation may be still in the mempool => counter from the node will be reused => counter duplicate error

Solutions:
1. Track counter globally, i.e. introduce a global pytezos context living during the entire execution (will cause many troubles in interactive mode)
2. Check mempool in order to eliminate counter duplicate issues (here https://github.com/baking-bad/pytezos/blob/0b7f12ce5adf574f578935d56938f5a0032e7610/pytezos/context/impl.py#L70)
