### ISSUE TITLE
Operation ttl semantics

### ISSUE THREAD

**Issue by dorranh** [baking-bad/pytezos#229]
In [this commit](https://github.com/baking-bad/pytezos/commit/7d877814fcb7807bb79e31e8ed13dbcfca30f451#diff-ecdce41445c551394fd5c29fb7cd6cd18271bde22c4bf0a31cfaf597eb4c1a50R130) from a few months ago, the api of `pytezos.operation.group.fill()` was changed to accept a `ttl` argument in place of the older `branch_offset` argument. This commit also changed the logic of how the branch's hash is found, computing the offset by subtracting the provided ttl value from the `MAX_OPERATIONS_TTL` constant. I just wanted to confirm that the current implementation is behaving as intended.

Thanks!

**Comment by m-kus** [comment]
Yes, it was made purely for better ux, the concept of "branch" is often misunderstood.
Current behavior is to use `head-{60-ttl}` block as branch so that the transaction will live for ~5 mins in mempool (at most).
For sandbox we continue to use `head` as branch.

There are two reasons:
1. Older branch ensures no problems with reorgs
2. Older branch reduces the time to wait until stuck operation is dropped

**Comment by dorranh** [comment]
Okay great, just wanted to double check. Thanks for the additional background info!
